//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int production_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity_produced { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public string batch_number { get; set; }
        public Nullable<bool> quality_check_passed { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
