//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int sale_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity_sold { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
