//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int supply_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity_received { get; set; }
        public Nullable<System.DateTime> supply_date { get; set; }
        public Nullable<int> supplier_id { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
